# Generated by Django 5.1.1 on 2024-11-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_myuser_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='about_me',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.TextField(verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.TextField(verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='interests',
            field=models.TextField(verbose_name='Интересы'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.TextField(verbose_name='Телефон'),
        ),
    ]
