# Generated by Django 5.1.1 on 2024-11-16 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_myuser_about_me_alter_myuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True, max_length=300)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.post_image', verbose_name='Фото к посту')),
            ],
        ),
    ]
